Implement single event listener for Touchable components to boost performance
react-native-tvos/react-native-tvos pull request #259
Opened 2022-01-24 16:56 UTC by Zahoq

## Summary

Each Touchable component needlessly creates own event listener, which, after focus transition, results in multiple handlers called just to check if event should be even handled by particular component. Performance of focus transition can be improved.

## Changelog

[General] [Changed] - Improved focus transition performance of Touchable components by introducing single Event Listener for all Touchables, instead of one Event Listener per Touchable.

## Test Plan

I've prepared simple TV app with improvement implemented as a patch to check and measure performance improvement. Rough measurement of focus transition between tiles on AndroidTV emulator indicates that time between onBlur -> onFocus pair reduced from ~11 ms to ~7 ms on average, and peak value form ~48 ms to ~14 ms.
https://github.com/Zahoq/TouchableFocusImprovementTestApp

2022-01-24 18:20 UTC, douglowder commented
This looks great. Could you also modify `Libraries/Components/Pressable/Pressable.js` to use the new focus handler?

2022-01-24 18:21 UTC, douglowder requested changes
This looks great. Could you also modify `Libraries/Components/Pressable/Pressable.js` to use the new focus handler?

2022-01-24 19:08 UTC, Zahoq commented
> This looks great. Could you also modify `Libraries/Components/Pressable/Pressable.js` to use the new focus handler?
Sure. I'll move initialization of `TVFocusEventHandler` instance to `TVFocusEventHandler.js` so both Touchables and Pressables use same instance of that class.

2022-01-27 03:00 UTC, douglowder approved these changes
LGTM, tested fine in simulator

2022-01-27 03:01 UTC, merged