Add support for Page Up / Page down (channel buttons) on iOS remote control
react-native-tvos/react-native-tvos pull request #267
Opened 2022-03-01 21:12 UTC by BryanRolfe

## Summary

This adds support for the Channel Up/Down buttons on the iOS control center remote control.

## Changelog

[TVOS] [Added] - Add support for Channel Up/Down buttons on iOS control center remote control.

## Test Plan

Add a TV event handler that logs eventType, open the Apple TV remote on an iPhone and press channel up/down to see the new pageUp/Down events

2022-03-04 03:31 UTC, douglowder commented
Thanks a lot @BryanRolfe !!! I'll test this out and get it merged soon.

2022-03-04 21:24 UTC, douglowder requested changes
See inline comments

2022-03-04 21:24 UTC, douglowder commented on React/Base/RCTTVRemoteHandler.m
> +      [self addTapGestureRecognizerWithSelector:@selector(tappePagedUp:)
Please change `tappePagedUp` -> `tappedPageUp`

2022-03-04 21:24 UTC, douglowder commented on React/Base/RCTTVRemoteHandler.m
> +NSString *const RCTTVRemoteEventPageUp = @"pageUp";
Could you please also add these as `extern` lines in `React/Base/RCTTVRemoteHandler.h`?

2022-03-11 20:29 UTC, douglowder approved these changes

2022-03-11 20:30 UTC, merged

2022-03-11 20:33 UTC, BryanRolfe commented
Thanks @douglowder - I was going to take care of these changes this weekend but you beat me to it!

2022-03-11 20:36 UTC, douglowder commented
NP @BryanRolfe and thanks again for adding this!