feat(accessibility): add focus accessibility action support
react-native-tvos/react-native-tvos pull request #643
Opened 2024-01-24 11:20 UTC by pierpo

## Summary:

I am working on a spatial navigation library. You can see this lib as the "Flutter of spatial navigation", as it completely bypasses the native focus to implement our own navigation logic in JS. The benefit being the same as Flutter: it is fully cross-platform with a fully predictible behaviour on all platforms.

Our problem (similar to Flutter, once again 😁 ): the accessibility support is poor.
If you enable TalkBack on Android, our focus system breaks. TalkBack takes over, and the user is stuck with elements that don't move anymore.

The workaround I could think of was to detect the accessibillity focus changes, and propagate them to our lib.

Problem: an event is missing. I opened a PR in React Native but I have no answer. https://github.com/facebook/react-native/pull/41336
Still, this might be a problem for developers working on React Native TV.

As the patch is very simple, I thought we might integrate it here directly.

## Changelog:

[ANDROID] [ADDED] - add accessibilityFocus action support

## Test Plan:

See https://github.com/facebook/react-native/pull/41336

2024-02-04 22:19 UTC, douglowder commented
@pierpo this change seems quite reasonable to me. Sorry for the delay, I have been ill.

@yusufyildirim should also review this.

2024-02-04 22:26 UTC, douglowder approved these changes

2024-02-05 09:57 UTC, pierpo commented
> @pierpo this change seems quite reasonable to me. Sorry for the delay, I have been ill.

Thank you so much! So sorry for being pushy 😱
I hope you are doing better 👍

2024-02-05 13:45 UTC, robingullo commented
@douglowder If it's not too much to ask, could you also release this a 0.72.6-2 patch ? That would be a great help for my team 😃

2024-02-13 02:52 UTC, douglowder requested changes
See comments inline

2024-02-13 02:53 UTC, douglowder commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
@pierpo can you add support for blur events?

2024-02-13 10:15 UTC, pierpo commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
Sure, I'll have a look! Many thanks to both of you for the review :)
I'll try this on TextInputs as well!

2024-02-15 15:03 UTC, pierpo commented
It works on TextInput 😊 

https://github.com/react-native-tvos/react-native-tvos/assets/6313316/ead278db-777e-4122-a6c5-5275658e08ba

2024-02-15 15:17 UTC, pierpo commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
I tried the `ACTION_CLEAR_ACCESSIBILITY_FOCUS` but it never triggers 😢 
I'm not sure it works the way we think. Doc isn't very explicit about it.

I can't find any other event that would make sense as an accessibility blur 🤔

2024-02-15 15:29 UTC, yusufyildirim commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
Thanks for looking into it! I'll test the PR whenever I can.

2024-03-26 17:13 UTC, pierpo commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
Hey @yusufyildirim! Any news on the testing? 😁 
Thank you! 🙏

2024-07-19 15:54 UTC, pierpo commented on packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactAccessibilityDelegate.java
> +    sActionIdMap.put("accessibilityFocus", AccessibilityActionCompat.ACTION_ACCESSIBILITY_FOCUS.getId());
Hello 😁 Bumping again! If you ever have the time to test it, we'd be super grateful 😊 
Thanks 🙏

2024-07-22 10:32 UTC, yusufyildirim approved these changes
Amazing stuff! I tested it and it works. Added a little bit of documentation to the README myself. Thank you for adding this and sorry for the long delay 🚀

2024-07-22 10:34 UTC, yusufyildirim commented
Let's not forget to cherrypick this for 0.74 and 0.75

2024-07-22 13:48 UTC, pierpo commented
Thank you! ❤️ That's awesome 😁

2024-07-22 17:56 UTC, douglowder approved these changes

2024-07-22 17:58 UTC, douglowder commented
@yusufyildirim @pierpo this looks great! Go ahead and merge, and I will cherry pick to 0.74 and get a release published.

2024-08-10 19:21 UTC, merged